### ISSUE TITLE
$products global called before the_post()

### ISSUE THREAD

**Issue by morganleek** [anttiviljami/woocommerce-facebook-conversion-pixel#1]
I've found that the global $product on line 81 (and possibly line 122) only return the product title and not the product object. This throws an error because it can't access the get_title method on the next line. I believe this is because they are called before the_post() function. According to the Woo docs the_post() function populates the global $product variable. Having said that this plugin looks really well written so perhaps the fault is my own. However I tried this on a fresh install with only Woo and the plugin.

To fix it I simply replaced `global $product` with 

`global $post;
 $product = wc_get_product( $post->ID );`

Also thanks for your great work, everything else worked really well and I love the plugin.

**Comment by anttiviljami** [comment]
Thanks for the bug report! :+1: 

I'll have to look into this. What you're telling me sounds possible, but it's weird that I haven't noticed it before. I should probably just run this with WP_DEBUG on again.

Cheers!

**Comment by scottbasgaard** [comment]
Any updates on this one? @anttiviljami

**Comment by albertpak** [comment]
confirmed - when i activated this plugin - it was making my product pages blank - but fix proposed by @morganleek made it all work :)

**Comment by anttiviljami** [comment]
Cool. Thanks! :) Can somebody PR?

**Comment by albertpak** [comment]
created a PR #2 - @anttiviljami pls review whenever you have time
